// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdcuucdblvxrzjbyuxbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkY3V1Y2RibHZ4cnpqYnl1eGJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDc4MzYsImV4cCI6MjA2MDQ4MzgzNn0.p4CLkjVTgYR4JcJJmRCsXkovZV5mVpclGDtr3TcVlk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);